version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html"
    ports:
      - "8080:80"
    environment: 
      PHP_IDE_CONFIG: "serverName=bs"
      XDEBUG_SESSION: "xdebug_is_great"
  mysql-server:
    image: mysql:5.7.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
      - "./mysql_sql:/root/mysql_sql"
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "5000:80"
  nginx:
    build:
      dockerfile: nginx.Dockerfile
      context: .
    restart: always
    volumes:
      - "./nginx_html:/usr/share/nginx/html"
      - "./nginx_conf:/etc/nginx/templates"
    ports:
      - "80:80"
      - "443:443"
    environment: 
      - NGINX_PORT=80
volumes:
  mysql-data:
